// // src/features/payment/Payment_Tally_Slice.js
// import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

// const BASE_URL = import.meta.env.VITE_BACKEND_URL || 'http://localhost:5000';

// export const paymentTallyApi = createApi({
//   reducerPath: 'paymentTallyApi',
//   baseQuery: fetchBaseQuery({
//     baseUrl: BASE_URL,
//     prepareHeaders: (headers) => {
//       // Agar future mein token add karna ho to yahan kar sakte ho
//       return headers;
//     },
//   }),
//   tagTypes: ['PaymentTally'],
//   endpoints: (builder) => ({
//     // Yeh tumhari /Get-Payment API ko hit karega
//     getPendingPayments: builder.query({
//       query: () => '/api/Get-Payment',  // ← Ye route tumhare backend mein registered hona chahiye
//       providesTags: ['PaymentTally'],

//       // Response ko clean aur predictable banane ke liye transform
//       transformResponse: (response) => {
//         console.log('[RTK] Pending Payments Raw Response:', response);

//         if (response?.success) {
//           return {
//             data: response.data || [],              // Full rows (filtered pending bills)
//             uniqueContractors: response.uniqueContractors || [], // [{ contractorName, firmName }]
//             count: response.count || 0,
//             message: response.message || '',
//           };
//         }

//         // Agar success false hai ya error aaya
//         return {
//           data: [],
//           uniqueContractors: [],
//           count: 0,
//           message: response?.message || 'Failed to fetch pending payments',
//         };
//       },
//     }),
//   }),
// });

// // Export hooks (automatically generated by RTK Query)
// export const {
//   useGetPendingPaymentsQuery,        // ← Main hook jo tum component mein use karoge
// } = paymentTallyApi;




/////////////////////////////////////////////////////////////////////////////////////////



// src/features/payment/Payment_Tally_Slice.js
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

const BASE_URL = import.meta.env.VITE_BACKEND_URL || 'http://localhost:5000';

export const paymentTallyApi = createApi({
  reducerPath: 'paymentTallyApi',
  baseQuery: fetchBaseQuery({
    baseUrl: BASE_URL,
  }),
  tagTypes: ['PaymentTally'],
  endpoints: (builder) => ({
    // 1. डेटा GET करने के लिए (मौजूदा)
    getPendingPayments: builder.query({
      query: () => '/api/Get-Payment',
      providesTags: ['PaymentTally'],
      transformResponse: (response) => {
        if (response?.success) {
          return {
            data: response.data || [],
            uniqueContractors: response.uniqueContractors || [],
            count: response.count || 0,
            message: response.message || '',
          };
        }
        return { data: [], uniqueContractors: [], count: 0, message: 'Failed to fetch' };
      },
    }),

    // 2. डेटा POST (Update) करने के लिए (नया)
    updatePayments: builder.mutation({
      query: (paymentDataArray) => ({
        url: '/api/Update-Payment', // आपका backend route
        method: 'POST',
        body: paymentDataArray, // यहाँ Array of objects जाएगा
      }),
      // जब पेमेंट सफल हो जाए, तो 'PaymentTally' वाले queries को रिफ्रेश करो
      invalidatesTags: ['PaymentTally'],
    }),
  }),
});

// Hooks एक्सपोर्ट करें
export const {
  useGetPendingPaymentsQuery,
  useUpdatePaymentsMutation, // ← नया हुक
} = paymentTallyApi;