// src/features/payment/Payment_Tally_Slice.js
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

const BASE_URL = import.meta.env.VITE_BACKEND_URL || 'http://localhost:5000';

export const paymentTallyApi = createApi({
  reducerPath: 'paymentTallyApi',
  baseQuery: fetchBaseQuery({
    baseUrl: BASE_URL,
    prepareHeaders: (headers) => {
      // Agar future mein token add karna ho to yahan kar sakte ho
      return headers;
    },
  }),
  tagTypes: ['PaymentTally'],
  endpoints: (builder) => ({
    // Yeh tumhari /Get-Payment API ko hit karega
    getPendingPayments: builder.query({
      query: () => '/api/Get-Payment',  // ← Ye route tumhare backend mein registered hona chahiye
      providesTags: ['PaymentTally'],

      // Response ko clean aur predictable banane ke liye transform
      transformResponse: (response) => {
        console.log('[RTK] Pending Payments Raw Response:', response);

        if (response?.success) {
          return {
            data: response.data || [],              // Full rows (filtered pending bills)
            uniqueContractors: response.uniqueContractors || [], // [{ contractorName, firmName }]
            count: response.count || 0,
            message: response.message || '',
          };
        }

        // Agar success false hai ya error aaya
        return {
          data: [],
          uniqueContractors: [],
          count: 0,
          message: response?.message || 'Failed to fetch pending payments',
        };
      },
    }),
  }),
});

// Export hooks (automatically generated by RTK Query)
export const {
  useGetPendingPaymentsQuery,        // ← Main hook jo tum component mein use karoge
} = paymentTallyApi;